### ISSUE TITLE
Fail to luanch using CentOS 8 stream

### ISSUE THREAD

**Issue by acyanbird** [fifty-six/Scarab#117]
### Scarab Version

v1.19.0.0 

### Hollow Knight Version

v1.5.7811833

### Steps to Reproduce

Fail to launch with CentOS 8 stream, cannot start when I extract all the files inside linux.zip and put them to the game directory.

This is my dotnet info

Version:   6.0.100-rc.2.21503.1
 Commit:    28be3e9a00

 OS Name:     centos
 OS Version:  8
 OS Platform: Linux
 RID:         centos.8-x64
 Base Path:   /usr/lib64/dotnet/sdk/6.0.100-rc.2.21503.1/

Host (useful for support):
  Version: 6.0.0-rc.2.21470.23
  Commit:  826f81a11a

.NET SDKs installed:
  6.0.100-rc.2.21503.1 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.2.21470.37 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21470.23 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### Expected Behaviour

start normally 

### Actual Behaviour

crash

### Logs

[ModInstaller.log](https://github.com/fifty-six/Scarab/files/10136628/ModInstaller.log)

**Comment by fifty-six** [comment]
Hey, I *believe* this is a known thing with Linux and Avalonia that I haven't worked around yet. It defaults to using some Microsoft fonts and so without them installed it can crash or show blanks. I'm not exactly sure about the process for CentOS but I believe if you install them it should fix itself.

**Comment by acyanbird** [comment]
still not working when i install it through
dotnet new install Avalonia.Templates
installation for avalonia is success, or there is not the correct way to install it?

I'm using .net 7.0 through snap now

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

运行时环境:
 OS Name:     centos
 OS Version:  8
 OS Platform: Linux
 RID:         centos.8-x64
 Base Path:   /var/lib/snapd/snap/dotnet-sdk/186/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/var/lib/snapd/snap/dotnet-sdk/186/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/var/lib/snapd/snap/dotnet-sdk/186/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/var/lib/snapd/snap/dotnet-sdk/186/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/snap/dotnet-sdk/current]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by acyanbird** [comment]
[ModInstaller.log](https://github.com/fifty-six/Scarab/files/10137037/ModInstaller.log)
here is the log, i believe it is exactly same(

**Comment by fifty-six** [comment]
I don't mean install Avalonia, I mean installing the ms fonts like Arial, Calibre, Times New Roman, etc. For CentOS, I believe [this](https://www.howtogeek.com/769894/how-to-install-google-and-microsoft-fonts-on-linux/) describes it, though I haven't used it myself.

**Comment by acyanbird** [comment]
still not working after installing these fonts, i also installed Segoe UI in case...

The error is also the same, cannot found fonts

**Comment by fifty-six** [comment]
Hey, sorry for the wait and all - was busy with exams and got sick and some other stuff. According to [this](https://github.com/AvaloniaUI/Avalonia/issues/4427#issuecomment-761074576), some people have had luck setting a locale env variable before running the app. Could you try giving that a shot? It would just be `LC_ALL=C ./Scarab`

**Comment by acyanbird** [comment]
it solved, thank you so much!!!
